application: tanaka-bot
version: 3
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /mention
  script: mention.py

- url: /.*
  script: main.py

libraries:
- name: webapp2
  version: "2.5.2"
